[package]
name = "ac-testing-sync"
version = "0.18.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
license = "Apache-2.0"
edition = "2021"

[dev-dependencies]
# Substrate dependencies
sp-application-crypto = { version = "37.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-core = { version = "34.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-runtime = { version = "38.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }

# local deps
substrate-api-client = { path = "../..", version = "0.18", default-features = false, features = ["tungstenite-client", "ws-client", "disable-metadata-hash-check"] }
ac-keystore = { path = "../../keystore", version = "0.18" }
