[package]
name = "ac-testing-async"
version = "0.18.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
license = "Apache-2.0"
edition = "2021"

[dev-dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", features = ['derive'] }
tokio = { version = "1.24", features = ["rt-multi-thread", "macros", "time"] }
jsonrpsee = { version = "0.22", features = ["async-client", "client-ws-transport-native-tls", "jsonrpsee-types", "server"] }


# Substrate dependencies
frame-support = { version = "35.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
kitchensink-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-core = { version = "34.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-crypto-hashing = { version = "0.1.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-keyring = { version = "38.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-runtime = { version = "38.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-staking = { version = "33.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
pallet-balances = { version = "36.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
pallet-staking = { version = "35.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }

# local deps
substrate-api-client = { path = "../..", version = "0.18", features = ["staking-xt", "contracts-xt", "disable-metadata-hash-check"] }
