[package]
name = "ac-keystore"
version = "0.10.1"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
license = "Apache-2.0"
edition = "2021"
repository = "https://github.com/scs/substrate-api-client"
description = "Keystore (and session key management) for ed25519 based chains like Polkadot. (fork of sc-keystore)"
readme = "README.md"

[dependencies]
array-bytes = "6.2"
async-trait = "0.1.52"
parking_lot = "0.12.0"
serde_json = "1.0.79"

# Substrate dependencies
sc-keystore = { version = "27.0.0" }
sp-application-crypto = { version = "32.0.0" }
sp-core = { version = "30.0.0" }
sp-keyring = { version = "33.0.0" }
sp-keystore = { version = "0.36.0" }

[dev-dependencies]
tempfile = "3.3.0"
