[package]
name = "ac-examples-wasm"
version = "0.18.0"
license = "Apache-2.0"
edition = "2021"

[dev-dependencies]
sp-core = { default-features = false, features = ["full_crypto", "serde"], version = "34.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-runtime = { default-features = false, version = "38.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
pallet-balances = { default-features = false, version = "36.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }

substrate-api-client = { path = "../..", version = "0.18", default-features = false }