[package]
name = "ac-examples-sync"
version = "0.5.0"
license = "Apache-2.0"
edition = "2021"

[dev-dependencies]
env_logger = "0.11"
log = "0.4.14"

# Substrate dependencies
sp-core = { version = "34.0.0" }
sp-keyring = { version = "38.0.0" }
sp-runtime = { version = "38.0.0" }
sp-weights = { version = "31.0.0" }

# local deps
substrate-api-client = { version = "0.17", default-features = false, features = ["tungstenite-client", "ws-client"] }
