[package]
name = "ac-examples-sync"
version = "0.5.0"
license = "Apache-2.0"
edition = "2021"

[dev-dependencies]
env_logger = "0.11"
log = "0.4.14"

# Substrate dependencies
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.7.1" }
sp-keyring = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.7.1" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.7.1" }
sp-weights = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.7.1" }

# local deps
substrate-api-client = { path = "../..", default-features = false, features = ["tungstenite-client", "ws-client"] }
