[package]
name = "ac-examples-sync"
version = "0.18.0"
license = "Apache-2.0"
edition = "2021"

[dev-dependencies]
env_logger = "0.11"
log = "0.4.14"

# Substrate dependencies
sp-core = { version = "34.0.0" }
sp-keyring = { version = "39.0.0" }
sp-runtime = { version = "39.0.1" }
sp-weights = { version = "31.0.0" }

# local deps
substrate-api-client = { path = "../..", version = "0.18", default-features = false, features = ["tungstenite-client", "ws-client", "disable-metadata-hash-check"] }
